#! /bin/sh

xsetroot -cursor_name left_ptr

~/.fehbg &
pgrep -x sxhkd > /dev/null || sxhkd &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20 
bspc config bottom_padding      30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1'
