#! /bin/sh

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              20 

bspc config top_padding             20 
bspc config bottom_padding          10
bspc config right_padding           10
bspc config left_padding            10

bspc config split_ratio             0.52
bspc config focus_follows_pointer   true
bspc config pointer_modifier        true
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Firefox desktop='^2'

